version: '3.8'
services:
  client:
    build:
      context: ./
      target: development
    volumes:
      - .:/app
    command: bash -c "npm run start:client"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    tty: true
    stdin_open: true
  server:
    build:
      context: ./
      target: development
    volumes:
      - .:/app
    command: bash -c "npm run start:server:development"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on: 
      - db
    tty: true
    stdin_open: true
  db:
    image: mongo:4.4.5
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: unless-stopped